version: "3.7"
services:
  movie-app:
    container_name: movie-app
    image: nodejs
    restart: always
    build: .
    ports:
      - "7500:7500"
    links:
      - mongo
    networks:
      - mynet 

  web:
    container_name: mynginx
    image: nginx:latest
    ports: 
      - "8080:80"
    volumes:
      - ./src:/var/www/html  
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
    links:
      - "php:myphp"
    networks:
    - mynet 
  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    networks:
      - mynet   

volumes:
  database: {}

networks:
  mynet:
    driver: bridge